### ISSUE TITLE
No AMI creating 

### ISSUE THREAD

**Issue by khan5551** [miztiik/Serverless-AMI-Baker#10]
Hi,

I followed the document but not able to take Instance AMI
Instance Tags used - **AmiBackUp** = Yes and **Name** = Testing
I have only One EC2 and both EC2 and Lambda are in us-east-1 and I updated the region in the function 
// event.get('REGION_NAME', "**us-east-1**") //

-- **SNS Output is**  --
{"Images": [], "FailedAMIs": [], "Status": {"TotalImages": 0, "BakedImages": 0, "Description": "Success"}}

-- **Lambda Function Output is** --
Response
{
  "Images": [],
  "FailedAMIs": [],
  "Status": {
    "TotalImages": 0,
    "BakedImages": 0,
    "Description": "Success"
  }
}
**Function Logs**
START RequestId: 4daf4276-4fc1-45af-b212-c02e056be9b5 Version: $LATEST
 [INFO]/2021-05-15 22:07:44,315/botocore.credentials - Found credentials in environment variables.
 [INFO]/2021-05-15 22:07:46,086/root - Number of instances to create AMI = 0

what could be the issue?
Thanks

**Comment by khan5551** [comment]
My Bad - 
AmiBackUp  is case sensitive and it should be AMIBackUp

**Comment by miztiik** [comment]
> My Bad -
> AmiBackUp is case sensitive and it should be AMIBackUp

AWS Tags are CaSe sensitive:) How many times, have i fallen for that.
