### ISSUE TITLE
 ERROR: problem setting globalVars - 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by itskaranshah** [miztiik/Serverless-AMI-Baker#3]
tags, region are in place but still getting this error. @miztiik

**Comment by miztiik** [comment]
@roc1 Can you give the error message from Lambda, and on which line.
(or)
How to reproduce this error?

**Comment by miztiik** [comment]
Closing it. ReOpen if you are still facing issues, do remember to post the logs
