### ISSUE TITLE
ERROR: problem setting globalVars - 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by mani1soni** [miztiik/Serverless-AMI-Baker#7]
I got following errors--

    ERROR: problem setting globalVars - 'NoneType' object has no attribute 'get'

    [INFO]/2019-08-07 11:53:31,646/root - Number of instances to create AMI = 0

But instance and lamda function in same region. (I change the region in code).

**Comment by miztiik** [comment]
Check if you have set all the Global Variables correctly, If possible provide the full global variables you had submitted as input.

**Comment by mani1soni** [comment]
okay done, now I am successfully able to run code in lambda.
